version: "3.2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mariadb
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d